import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { createDb, type Db } from "./client.js";

/** `src/infra/db/migrations` (generated by `drizzle-kit generate`), resolved from both `src/` (tsx/vitest) and `dist/` (compiled image: `dist/infra/db` -> `../../../src/infra/db/migrations`). */
export function resolveMigrationsFolder(fromDir = dirname(fileURLToPath(import.meta.url))): string {
  return fromDir.includes(`${"/"}dist${"/"}`)
    ? join(fromDir, "..", "..", "..", "src", "infra", "db", "migrations")
    : join(fromDir, "migrations");
}

/** Applies pending migrations (drizzle tracks them in `drizzle.__drizzle_migrations`); safe to re-run. */
export async function runMigrations(db: Db, migrationsFolder = resolveMigrationsFolder()): Promise<void> {
  await migrate(db, { migrationsFolder });
}

/** One-shot CLI: `node dist/infra/db/migrate.js` (compose `bff-migrate` service; a one-off task in production). */
async function main(): Promise<void> {
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL is required to run migrations");
  const handle = createDb(url);
  try {
    await runMigrations(handle.db);
    console.log("migrations applied");
  } finally {
    await handle.close();
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main().catch((error: unknown) => {
    console.error(error);
    process.exit(1);
  });
}
